- docs/commerce/2.x/en/user-guide/marketing/adding-discounts-by-product.md
https://github.com/liferay/liferay-learn/issues/69
> Removed extra space to render image

- docs/dxp-cloud/latest/en/troubleshooting/disaster-recovery.md
Supersedes https://github.com/liferay/liferay-learn/pull/93
CC @bernarddeluna
> Updated DR article

- site/docs/_static/main.css
- site/docs/_templates/index.html
- site/docs/_templates/page.html
- site/homepage/_static/main.css
- site/homepage/_static/scss/_documentations.scss
- site/homepage/_templates/index.html
Pull it down, poke holes at it, make sure it works in all scenarios. :pray:
> DXP sidenav

- site/docs/_templates/page.html
fixes the dropdown on docs view.
> Correctly compare dropdown value

- site/docs/conf.py
should fix the missing additional links
> Disable auto toctree

- site/docs/_static/main.css
- site/docs/_templates/page.html
- site/homepage/_static/main.css
- site/homepage/_static/scss/_documentations.scss
> refactor left nav

- docs/dxp-cloud/latest/en/manage-and-optimize/auto-scaling.md
https://github.com/liferay/liferay-learn/pull/104/commits 
Wordsmithed and replaced "licenses" with "activation keys".
> Added "Handling Activation Keys" section

- site/docs/_static/main.css
- site/homepage/_static/main.css
- site/homepage/_static/scss/_admonition.scss
- site/homepage/_static/scss/_landing_page.scss
> More balanced landing page spacing

- docs/commerce/2.x/en/creating-store-content/commerce-storefront-pages/product-details.md
https://learn.liferay.com/commerce-2.x/creating-store-content/commerce-storefront-pages/product-details.html
While trying to search another problem, i found this one.
> Broken image link and note formatting.

- docs/dxp/7.x/en/landing.html
Small update to the changes from https://github.com/jrhoun/liferay-learn/pull/217  (fixing the links in the cards for the sections that have been reorganized)
> Update to cards & links

- docs/commerce/2.x/en/installation-and-upgrades/maintenance-versions.md
See https://issues.liferay.com/browse/LRDOCS-7748 and Commerce-1859
> Removed sentence on 'no new features'

- docs/dxp/7.x/en/installation-and-upgrades/installing-liferay/installing-liferay-on-an-application-server/installing-on-wildfly.md
https://issues.liferay.com/browse/LRDOCS-7898
> LRDOCS-7898 do not remove weld configuration from WildFly

- docs/dxp/7.x/en/landing.html
> Fix DXP landing page link to installing and managing apps

- docs/dxp/7.x/en/installation-and-upgrades/installing-liferay/using-liferay-dxp-docker-images/configuring-dxp-containers.md
> Fix docker cp command for .config files

- docs/dxp/7.x/en/installation-and-upgrades/securing-liferay/configuring-sso/authenticating-with-cas.md
Forwarding with no changes. 
@rbohl
> Cfg to Config

- docs/dxp/7.x/en/landing.html
https://issues.liferay.com/browse/LRDOCS-8540
> LRLDOCS-8540 fix link to breaking changes

- docs/dxp/7.x/en/installation-and-upgrades/upgrading-liferay/upgrade-basics/upgrading-via-docker.md
- docs/dxp/7.x/en/installation-and-upgrades/upgrading-liferay/upgrade-basics/using-the-database-upgrade-tool.md
- docs/dxp/7.x/en/using-search/installing-and-upgrading-a-search-engine/solr/solr-limitations.md
https://issues.liferay.com/browse/LRDOCS-8773
> LRDOCS-8773 Fix links

- docs/commerce/2.x/en/installation-and-upgrades/installing-commerce-2.1-and-below/using-the-liferay-commerce-tomcat-bundle.md
- docs/dxp/7.x/en/site-building/publishing-tools/publications/enabling-publications.md
This PR fixes two broken links ([LRDOCS-8871](https://issues.liferay.com/browse/LRDOCS-8871)):
1) [using-the-liferay-commerce-tomcat-bundle](https://github.com/jrhoun/liferay-learn/pull/882/commits/69e87409435f73890a78ab26c26aa680c5fe8742#diff-02e35a947ad2ee41b092878e5733a541283886e90db463be8d12b6373d03ed93)
2) [enabling-publications](https://github.com/JamesAGarcia/liferay-learn/pull/2/commits/8ddadf8ad201ee6b8a218ae925d7d894baf6df06)
cc @jhanda
> LRDOCS-8871 Fixes Broken Links

- docs/dxp/7.x/en/using-search/installing-and-upgrading-a-search-engine/elasticsearch.rst
- docs/dxp/7.x/en/using-search/installing-and-upgrading-a-search-engine/elasticsearch/upgrading_elasticsearch.rst
- docs/dxp/7.x/en/using-search/liferay_enterprise_search.rst
> search 7.x | minor fixes to nav and license info

- docs/dxp/7.x/en/using-search/liferay-enterprise-search/monitoring-elasticsearch.md
- site/build_site.sh
https://issues.liferay.com/browse/LRDOCS-9142
cc @lipusz
> search 7.2 | monitoring settings fix | LRDOCS-9142

- docs/dxp/7.x/en/installation-and-upgrades/reference/liferay-upgrade-planner-steps.md
- docs/dxp/7.x/ja/installation-and-upgrades/reference/liferay-upgrade-planner-steps.md
- docs/dxp/7.x/ja/installation-and-upgrades/upgrading-liferay-dxp/reference/liferay-upgrade-planner-steps.md
- site/docs/redirects.json
We decided a long time ago to do away with this article but I hadn't removed its placeholder. It's presence is causing people confusion.
https://issues.liferay.com/browse/LRDOCS-9015
> LRDOCS-9015 Replace unwanted "Liferay Upgrade Planner Steps" articles with redirects

- docs/dxp/7.x/en/installation-and-upgrades/upgrading-liferay/configuration-and-infrastructure/migrating-configurations-and-properties.md
- docs/dxp/7.x/en/installation-and-upgrades/upgrading-liferay/upgrade-basics/upgrade-overview.md
https://issues.liferay.com/browse/LRDOCS-9136
Forwarding with no changes. 
@jhinkey, if you have small changes like this, please send them directly to @jrhoun. Thanks!
> LRDOCS-9136 Admonish users to migrate their "locales" property.

- docs/dxp/latest/en/developing-applications/core-frameworks/configurable_application.rst
https://issues.liferay.com/browse/LRDOCS-7841
Small fix for links in RST file. Still working on articles so please keep the Jira ticket open. Thanks!
> LRDOCS-7841 RST Fix

- docs/commerce/latest/en/installation-and-upgrades/activating-liferay-commerce-enterprise.md
Corrected error on Portal Property. 
Thanks
> LRDOCS-9818 Portal Property Corrected

- docs/_template/js/setup_tutorial.sh
- docs/dxp/latest/en/using-search/liferay-enterprise-search/cross-cluster-replication/configuring-an-example-ccr-installation-replicating-between-data-centers.md
https://issues.liferay.com/browse/LRDOCS-10084
> search 7.x | fix typo in ccr docs | LRDOCS-10084

- docs/dxp/latest/en/building-applications/landing.html
- docs/dxp/latest/en/building-applications/remote-apps.md
- docs/dxp/latest/en/building-applications/remote-apps/landing.html
- site/homepage/robots.txt
This fixes two typos related to LRDOCS-10099 and adds the article to the Building Applications landing page.
> Fixes related to LRDOCS-10099

- docs/dxp/latest/en/using-search/search-pages-and-widgets/similar-results.md
https://issues.liferay.com/browse/LRDOCS-10232
Follow-up since it's not yet in 7.3. cc @lipusz
> search 7.x | similar results scope selector | LRDOCS-10232

- docs/dxp/latest/en/content-authoring-and-management/content-dashboard.md
- docs/dxp/latest/en/process-automation/workflow/using-workflows/using-workflow-metrics.md
- docs/dxp/latest/en/using-search/installing-and-upgrading-a-search-engine/solr/solr-limitations.md
- docs/dxp/latest/en/using-search/search-administration-and-tuning/result-rankings.md
- docs/dxp/latest/en/using-search/search-administration-and-tuning/synonym-sets.md
- docs/dxp/latest/en/using-search/search-pages-and-widgets/search-results/custom-filter-examples.md
- docs/dxp/latest/en/using-search/search-pages-and-widgets/search-results/filtering-search-results.md
- docs/dxp/latest/en/using-search/search-pages-and-widgets/similar-results.md
https://issues.liferay.com/browse/LRDOCS-10562
cc @lipusz
> search 7.x | search engine availability | LRDOCS-10562
